<?php
/**
 * @file
 * Contains base function for module.
 */

/**
 * Implements hook_menu().
 */
function count_login_menu() {
  $items = array();
  $items['count_login_table_date'] = array(
    'title' => 'Table with dates',
    'page callback' => 'count_login_table_date_page',
    'access arguments' => array('administer site configuration'),
  );
  $items['count_login_table_value'] = array(
    'title' => 'Table with values',
    'page callback' => 'count_login_table_values_page',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Generates a table to display.
 */
function count_login_table_date_page() {
  $header = array(t('username'), t('date')); 
  $rows = array();
  $query = db_select('count_login_values', 't')
    ->fields('t', array('username', 'date'))
    ->execute(); 
  while ($value = $query->fetchAssoc()) {
    $rows[] = array(
      'username' => $value['username'],
      'date' => date("F j, Y, g:i a", $value['date']),
    );
  }
  return theme('table', array('header' => $header, 'rows' => $rows));
} 

function count_login_table_values_page() {
  $header = array(t('username'), t('value'));
  $rows = array();
  $count = array();
  $query = db_select('count_login_values', 'n')
    ->fields('n', array('username', 'uid'))
    ->execute(); 
  while ($value = $query->fetchAssoc()) {
    if (isset($count[$value['username']]))  {
      $count[$value['username']]++;
    }
    else {
      $count[$value['username']] = 1;
    }
   }
   foreach ($count as $key => $value)
   $rows[] = array(
     'username' => $key,
     'value' => $value,
   );
  return theme('table', array('header' => $header, 'rows' => $rows)); 
} 
/**
 * Implements hook_user_login().
 */
function count_login_user_login(&$edit, $account) {
    count_login_login_count_insert($account->uid);
}

/**
 * Insert entries to the database.
 */
function count_login_login_count_insert($uid) {
   global $user;
   $query = db_insert('count_login_values')
     ->fields(array(
       'username' => $user->name,
       'uid' => $uid,
       'date' => time(),
     ))
     ->execute();
 }  
 


