<?php
/**
 * @file
 * Contains base function for module.
 */

 /**
 * Implements hook_menu().
 */
function count_login_menu() {
  $items = array();
  $items['count_login_table'] = array(
    'title' => 'Table with data',
    'page callback' => 'count_login_table_data_page',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function cmp($a, $b) {
    if ($a == $b) {
        return 0;
    }
    return ($a < $b) ? -1 : 1;
}

function count_login_table_data_page() {
  $header = array(t('username'), t('value'), t('date'));
  $rows = array();
  $counter = db_select('count_login_values', 't')
    ->fields('t', array('uid'))
    ->execute();
  $count = array();  
  while ($value = $counter->fetchAssoc()) {
    if (isset($count[$value['uid']])) {
      $count[$value['uid']]++;
    }
    else {
      $count[$value['uid']] = 1;
    }
  }
  $query = db_select('count_login_values', 't')
    ->fields('t', array('username', 'date', 'uid'))
    ->execute();
  while ($value = $query->fetchAssoc()) {
    $rows[] = array(
      'username' => $value['username'],
      'value' => $count[$value['uid']],
      'date' => date("F j, Y, g:i a", $value['date']),
    ); 
  }
  uasort($rows, 'cmp');
  return theme('table', array('header' => $header, 'rows' => $rows));
} 

function count_login_isset($uid) {
  $result = db_query("SELECT COUNT(*)
    FROM {count_login_values}
    WHERE uid = :uid",
    array(
      ':uid' => $uid,
    ))
    ->fetchField();
  if ($result > 0) {
    return TRUE;
  }
  return FALSE;
}

 
/**
 * Implements hook_user_login().
 */
function count_login_user_login(&$edit, $account) {
  if (variable_get('count_login_count_logins', TRUE)) {
    count_login_login_count_insert($account->uid);
  }
}

/**
 * Manage the login count of a given user.
 */
function count_login_login_count_insert($uid) {
   global $user;
   if (count_login_isset($uid)){
     $query = db_insert('count_login_values')
     ->fields(array(
       'uid' => $uid,
       'date' => time(),
     ))
     ->execute(); 
   }
   else {
    $query = db_insert('count_login_values')
      ->fields(array(
        'username' => $user->name,
        'uid' => $uid,
        'date' => time(),
      ))
      ->execute();
   }
 }  
 


